### ISSUE TITLE
bug: webrtc circuit relay addresses not passing Circuit matcher

### ISSUE THREAD

**Issue by SgtPooki** [multiformats/js-multiaddr-matcher#36]
i'm working on https://github.com/ipfs-shipyard/ipfs-share-files/pull/138 and noticed that when I was trying to render the count of Circuit relay addresses, `Circuit.matches(addr)` was failing for some addresses that pass when checked with `addr.toString().includes('p2p-circuit')` 

Looking at the tests, I see that some `goodWebRTC` in the tests include similar addresses, but those addresses do not pass the circuit matcher test when added to `goodCircuit`

I think this is a bug with this matcher and not js-libp2p because they exist in `goodWebRTC` but I am opening this issue to track my experience. I will open up a PR to fix the circuit checker to work pass with the ciruit-relay addresses in the `goodWebRTC` list 

references:

https://github.com/multiformats/js-multiaddr-matcher/blob/3d8210d03356b2a0b6deaddee2b61e335bbc5e51/test/index.spec.ts#L217-L218

https://github.com/multiformats/js-multiaddr-matcher/blob/3d8210d03356b2a0b6deaddee2b61e335bbc5e51/test/index.spec.ts#L160C9-L160C20

**Comment by achingbrain** [comment]
If you're trying to count the number of circuit relay addresses (actual circuit relay, not addresses that have a circuit-relay component like WebRTC), use `Circuit.exactMatch(addr)`.

Are you trying to count WebRTC addresses as Circuit Relay addresses?

**Comment by SgtPooki** [comment]
I was trying to get the count of Circuit relay addresses I was listening on, and all of my addresses were circuit relay addresses (makes sense in the browser) but `Circuit.matches` was returning false for some. Based on your answer, I think this is expected behavior and we can close this and #37.

**Comment by achingbrain** [comment]
I think for share.ipfs.tech we're more interested in WebRTC addresses, right?  Bitswap won't run over limited connections like ones via relays so they aren't much use for sharing files.
